---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: default
  labels:
    app: ghost
spec:
  selector:
    matchLabels:
      app: ghost
  replicas: 1
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: '{{.Values.imagelocation.domainname}}/{{.Values.imagelocation.project}}/ghost:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2368
          env:
            - name: url
              value: http://localhost:32593
---
apiVersion: v1
kind: Service
metadata:
  name: ghost-svc
  namespace: default
  labels:
    svc: ghost-svc
spec:
  type: NodePort
  ports:
    - port: 2368
      name: function1
      targetPort: 2368
      protocol: TCP
      nodePort: 32593
  selector:
    app: ghost