apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: default
  labels:
    app: nextcloud
spec:
  selector:
    matchLabels:
      app: nextcloud
  replicas: 1
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: '{{.Values.imagelocation.domainname}}/{{.Values.imagelocation.project}}/nextcloud:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-svc
  namespace: default
  labels:
    svc: nextcloud-svc
spec:
  type: NodePort
  ports:
    - port: 80
      name: function1
      targetPort: 80
      protocol: TCP
      nodePort: 32700
  selector:
    app: nextcloud
