---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sudoku
  namespace: default
  labels:
    app: sudoku
spec:
  selector:
    matchLabels:
      app: sudoku
  replicas: 1
  template:
    metadata:
      labels:
        app: sudoku
    spec:
      containers:
        - name: sudoku
          image: '{{.Values.imagelocation.domainname}}/{{.Values.imagelocation.project}}/sudoku:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sudoku-svc
  namespace: default
  labels:
    svc: sudoku-svc
spec:
  type: NodePort
  ports:
    - port: 80
      name: function1
      targetPort: 80
      protocol: TCP
      nodePort: 32597
  selector:
    app: sudoku

