---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
  namespace: default
  labels:
    app: mediawiki
spec:
  selector:
    matchLabels:
      app: mediawiki
  replicas: 1
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
        - name: mediawiki
          image: '{{.Values.imagelocation.domainname}}/{{.Values.imagelocation.project}}/mediawiki:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki-svc
  namespace: default
  labels:
    svc: mediawiki-svc
spec:
  type: NodePort
  ports:
    - port: 80
      name: function1
      targetPort: 80
      protocol: TCP
      nodePort: 32683
  selector:
    app: mediawiki

