---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game2048
  namespace: default
  labels:
    app: game2048
spec:
  selector:
    matchLabels:
      app: game2048
  replicas: 1
  template:
    metadata:
      labels:
        app: game2048
    spec:
      containers:
        - name: game2048
          image: '{{.Values.imagelocation.domainname}}/{{.Values.imagelocation.project}}/game-2048:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: game2048-svc
  namespace: default
  labels:
    svc: game2048-svc
spec:
  type: NodePort
  ports:
    - port: 80
      name: function1
      targetPort: 80
      protocol: TCP
      nodePort: 32580
  selector:
    app: game2048

