---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman
  namespace: default
  labels:
    app: pacman
spec:
  selector:
    matchLabels:
      app: pacman
  replicas: 1
  template:
    metadata:
      labels:
        app: pacman
    spec:
      containers:
        - name: pacman
          image: '{{.Values.imagelocation.domainname}}/{{.Values.imagelocation.project}}/pacman:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pacman-svc
  namespace: default
  labels:
    svc: pacman-svc
spec:
  type: NodePort
  ports:
    - port: 80
      name: function1
      targetPort: 80
      protocol: TCP
      nodePort: 32595
  selector:
    app: pacman

