apiVersion: v1
kind: PersistentVolume
metadata:
  name: face-recognition-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/etc/face-recognition-data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: face-recognition-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: face-recognition-deployment
  labels:
    app: face-recognition
spec:
  containers:
  - name: face-recognition-app
    image: face_recognition_app:v1.4
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 9999
      protocol: TCP
  - name: face-recognition-postgresql
    image: postgres:9.6.15
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5432
      protocol: TCP
    env:
      - name: POSTGRESQL_USERNAME
        value: postgres
      - name: POSTGRESQL_PASSWORD
        value: "root"
    volumeMounts:
          - name: face-recognition-data
            mountPath: /postgres/data
  - name: face-recognition-redis      
    image: redis:alpine
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 6379
      protocol: TCP
  volumes:
        - name: face-recognition-data
          persistentVolumeClaim:
            claimName: face-recognition-pvc
       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: face-recognition
  name: face-recognition
spec:
  type: NodePort
  ports:
    - port: 9999
      targetPort: 9999
      name: face-recognition  
      nodePort: 32111  
  selector:
    app: face-recognition