#
# Copyright 2020 Huawei Technologies Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '3'   # compose-file的语法版本
services:    # 定义服务
  face-recognition-postgresql:
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - /home/mep/postgres/face_data:/var/lib/postgresql/data
  face-recognition-app:     # 指定服务1 web
    build: .    # 使用当前目录下的Dockerfile构建镜像
    ports:    # 指定端口映射
      - "9999:9999"
    container_name: face_recognition  # 容器名称 container_name+services_name 会作为镜像名称
    links:
      - face-recognition-postgresql
  face-recognition-redis:
    image: "redis:alpine"
    volumes:   # 指定数据卷
      - redis-data:/data
    container_name: redis
volumes:
    redis-data:
      driver: local
