version: '3'   # compose-file的语法版本
services:    # 定义服务
  face-recognition-postgresql:
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - /home/mep/postgres/face_data:/var/lib/postgresql/data
  face-recognition-app:     # 指定服务1 web
    build: .    # 使用当前目录下的Dockerfile构建镜像
    ports:    # 指定端口映射
      - "9999:9999"
    container_name: face_recognition  # 容器名称 container_name+services_name 会作为镜像名称
    links:
      - face-recognition-postgresql
  face-recognition-redis:
    image: "redis:alpine"
    volumes:   # 指定数据卷
      - redis-data:/data
    container_name: redis
volumes:
    redis-data:
      driver: local
