

version: '3'   # compose-file的语法版本
services:    # 定义服务
  face-recognition-postgresql:
    image: "postgres:9.6.15"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - /home/mep/postgres/face_data:/var/lib/postgresql/data
  face-recognition-app:     # 指定服务1 web
    image: "swr.ap-southeast-1.myhuaweicloud.com/edgegallery/face_recognition_app:v1.5"   # 使用当前目录下的Dockerfile构建镜像
    ports:    # 指定端口映射
      - "9999:9999"
    container_name: face_recognition  # 容器名称 container_name+services_name 会作为镜像名称
    environment:
      POSTGRES_HOST: face-recognition-postgresql
      REDIS_HOST: face-recognition-redis
  face-recognition-redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:   # 指定数据卷
      - redis-data:/data
    container_name: face-recognition-redis
volumes:
    redis-data:
      driver: local
