---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canvasbox
  namespace: default
  labels:
    app: canvasbox
spec:
  selector:
    matchLabels:
      app: canvasbox
  replicas: 1
  template:
    metadata:
      labels:
        app: canvasbox
    spec:
      containers:
        - name: canvasbox
          image: '{{.Values.imagelocation.domainname}}/{{.Values.imagelocation.project}}/canvasbox:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: canvasbox-svc
  namespace: default
  labels:
    svc: canvasbox-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32571
  selector:
    app: canvasbox

