---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake
  namespace: default
  labels:
    app: snake
spec:
  selector:
    matchLabels:
      app: snake
  replicas: 1
  template:
    metadata:
      labels:
        app: snake
    spec:
      containers:
        - name: snake
          image: '{{.Values.imagelocation.domainname}}/{{.Values.imagelocation.project}}/snake:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: snake-svc
  namespace: default
  labels:
    svc: snake-svc
spec:
  type: NodePort
  ports:
    - port: 80
      name: function1
      targetPort: 80
      protocol: TCP
      nodePort: 32582
  selector:
    app: snake

