---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: objectsizedetector
  namespace: '{{ .Values.appconfig.appnamespace }}'
  labels:
    app: objectsizedetector
spec:
  selector:
    matchLabels:
      app: objectsizedetector
  replicas: 1
  template:
    metadata:
      labels:
        app: objectsizedetector
    spec:
      containers:
        - name: objectsizedetector
          image: '{{.Values.imagelocation.domainname}}/{{.Values.imagelocation.project}}/object-size-detector:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: objectsizedetector-svc
  namespace: '{{ .Values.appconfig.appnamespace }}'
  labels:
    svc: objectsizedetector-svc
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 31669
  selector:
    app: objectsizedetector

