version: '3'
services:
  face-recognition-postgresql:
    image: "postgres:9.6.15"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    container_name: face-recognition-postgresql
  face-recognition:     
    image: "swr.ap-southeast-1.myhuaweicloud.com/edgegallery/face_recognition_app:v1.5"   
    ports:   
      - "9999:9999"
    container_name: face-recognition  
    environment:
      POSTGRES_HOST: face-recognition-postgresql
      REDIS_HOST: face-recognition-redis
  face-recognition-redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    container_name: face-recognition-redis
  monitoring-be-32115:
    image: "swr.ap-southeast-1.myhuaweicloud.com/edgegallery/monitoring-be-service:1.0"
    restart: always
    environment: 
      LISTEN_IP: 0.0.0.0
      FE_SERVICE: "monitoring-proxy-service:5000"
    ports:
      - "32115:9997"
  monitoring-fe-service-32116:
    image: "swr.ap-southeast-1.myhuaweicloud.com/edgegallery/monitoring-fe-service:1.0"
    restart: always
    ports:
      - "32116:8080" 
  monitoring-proxy-service-32117:
    image: "swr.ap-southeast-1.myhuaweicloud.com/edgegallery/monitoring-proxy-service:1.0"
    restart: always
    environment:
      EXPOSE_PORT: "32117"
    ports:
    - "32117:5000"
    container_name: monitoring-proxy-service