apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  namespace: default
  labels:
    app: drupal
spec:
  selector:
    matchLabels:
      app: drupal
  replicas: 1
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
        - name: drupal
          image: '{{.Values.imagelocation.domainname}}/{{.Values.imagelocation.project}}/drupal:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: drupal-svc
  namespace: default
  labels:
    svc: drupal-svc
spec:
  type: NodePort
  ports:
    - port: 80
      name: function1
      targetPort: 80
      protocol: TCP
      nodePort: 32702
  selector:
    app: drupal