---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: default
  labels:
    app: registry
spec:
  selector:
    matchLabels:
      app: registry
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: '{{.Values.imagelocation.domainname}}/{{.Values.imagelocation.project}}/registry:2'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: registry-svc
  namespace: default
  labels:
    svc: registry-svc
spec:
  type: NodePort
  ports:
    - port: 5000
      name: function1
      targetPort: 5000
      protocol: TCP
      nodePort: 32688
  selector:
    app: registry

