---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aixiaochu
  namespace: default
  labels:
    app: aixiaochu
spec:
  selector:
    matchLabels:
      app: aixiaochu
  replicas: 1
  template:
    metadata:
      labels:
        app: aixiaochu
    spec:
      containers:
        - name: aixiaochu
          image: '{{.Values.imagelocation.domainname}}/{{.Values.imagelocation.project}}/aixiaochu:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aixiaochu-svc
  namespace: default
  labels:
    svc: aixiaochu-svc
spec:
  type: NodePort
  ports:
    - port: 80
      name: function1
      targetPort: 80
      protocol: TCP
      nodePort: 32584
  selector:
    app: aixiaochu

