---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuiper
  namespace: default
  labels:
    app: kuiper
spec:
  selector:
    matchLabels:
      app: kuiper
  replicas: 1
  template:
    metadata:
      labels:
        app: kuiper
    spec:
      containers:
        - name: kuiper
          image: '{{.Values.imagelocation.domainname}}/{{.Values.imagelocation.project}}/kuiper:0.3.2'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9081 
---
apiVersion: v1
kind: Service
metadata:
  name: kuiper-svc
  namespace: default
  labels:
    svc: kuiper-svc
spec:
  type: NodePort
  ports:
    - port: 9081 
      name: function1
      targetPort: 9081 
      protocol: TCP
      nodePort: 32498
  selector:
    app: kuiper

