---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rdesktop
  namespace: default
  labels:
    app: rdesktop
spec:
  selector:
    matchLabels:
      app: rdesktop
  replicas: 1
  template:
    metadata:
      labels:
        app: rdesktop
    spec:
      containers:
        - name: rdesktop
          image: '{{.Values.imagelocation.domainname}}/{{.Values.imagelocation.project}}/rdesktop:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3389
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/London"
---
apiVersion: v1
kind: Service
metadata:
  name: rdesktop-svc
  namespace: default
  labels:
    svc: rdesktop-svc
spec:
  type: NodePort
  ports:
    - port: 3389
      name: webui
      targetPort: 3389
      protocol: TCP
      nodePort: 32621
  selector:
    app: rdesktop

