###spring config######
server:
  port: 9912
  ssl:
    enabled: ${SSL_ENABLED:false}
    protocol: TLS
    enabled-protocols: [TLSv1.2]
    ciphers: [TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
              TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384]
    key-store: ${SSL_KEY_STORE_PATH:}
    key-store-password: ${SSL_KEY_STORE_PASSWORD:}
    key-store-type: ${SSL_KEY_STORE_TYPE:}
    key-alias: ${SSL_KEY_ALIAS:}

  main:
    allow-bean-definition-overriding: true
